# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost #postgres://xqndcwcxncdymd:s5qm1oIwEDcr #localhost
  pool: 5
  username: postgres #<%= ENV["POSTGRESQL_USERNAME"] %>
  password: postgres #<%= ENV['POSTGRESQL_PASSWORD'] %>
  database: folhaprocesso_db #<%= ENV["POSTGRESQL_DATABASE"] %>


development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default
  database: folhaprocesso_test